In [22]:
import pandas as pd

In [23]:


df = pd.read_csv('harshdata.csv')

In [24]:
df

   sno    name  rollno address      moblie
0    1   harsh       1    durg  3321321512
1    2  pankaj       2  raipur    44455251

In [25]:
df["full address"]=df["address"]+" chhittisgarh"

In [26]:
df

   sno    name  rollno address      moblie         full address
0    1   harsh       1    durg  3321321512    durg chhittisgarh
1    2  pankaj       2  raipur    44455251  raipur chhittisgarh

In [27]:
df["rollno"]=int("31000222403")+df["rollno"]

In [28]:
df

   sno    name       rollno address      moblie         full address
0    1   harsh  31000222404    durg  3321321512    durg chhittisgarh
1    2  pankaj  31000222405  raipur    44455251  raipur chhittisgarh